### ISSUE TITLE
a small issue about this extension

### ISSUE THREAD

**Issue by RouChan** [xelad0m/vscode-jupyter-toc#2]
Hi there, 
Thanks for your brilliant extension, which greatly enhance my efficiency during programming.
However, I found that after inserting toc with your extension, the `OUTLINE` panel in vs code will have `empty cell` to mark the toc cell. (as you can see in the screenshot). 
<img width="732" alt="Screenshot 2022-12-01 at 20 39 08" src="https://user-images.githubusercontent.com/55694771/205055210-27f0b29b-742a-471e-ab1a-b9b97e8688f9.png">

**Comment by xelad0m** [comment]
Hi, I'm glad to hear that it turned out to be useful.  As I understand it, VS Code just take first string from every markdown cell in document to build outline panel content. I think in next update I`ll try to rearrange toc cell content so that the title of toc becomes the first line in toc cell.

**Comment by RouChan** [comment]
Sincere gratitude to your reply.

**Comment by xelad0m** [comment]
Fixed
